Transform: AWS::Serverless-2016-10-31

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: ruby2.5
      Timeout: 180
      Handler: handler.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref SimpleTable
      CodeUri: ../lib/cfn-least-privilege-role-generator/cloudtrail
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SimpleTable
      Events:
        CloudTrailEvent:
          Type: CloudWatchLogs
          Properties:
            LogGroupName: cfn-least-privilege-role-generator
            FilterPattern: '{$.sourceIPAddress = cloudformation.amazonaws.com}'
  SimpleTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: cfn-least-privilege-role-generator-events
      PrimaryKey:
        Name: RoleArn
        Type: String
      SSESpecification:
        SSEEnabled: true

